using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CONDUIT.DataLayer
{
    public class TEST_CONDUIT_DBContext : DbContext
    {
        /// <summary>
        /// Manually created DB Context class that defaults to the 'CONDUIT_Entities' connection string provided in either the app.config or web.config of executing program
        /// </summary>
        /// <param name="connection"></param>
        public TEST_CONDUIT_DBContext(string connection = "CONDUIT_Entities") : base(connection)
        {
            //connection is set to the name of the connection string, however, EF generated DBContext used "name=CONDUIT_Entities", this does not seem to matter though
        }

        /// <summary>
        /// Manually entered DBSet property that represents a table in this scenario.
        /// The users class used was generated by EF but can be created manually similar to the Users class commented out below
        /// </summary>
        public virtual DbSet<User> Users { get; set; }
    }
}

//namespace CONDUIT.DataLayer
//{
//    using System;
//    using System.Collections.Generic;

//    public partial class User
//    {
//        public int ID { get; set; }
//        public System.DateTime Created { get; set; }
//        public System.DateTime Modified { get; set; }
//        public bool Active { get; set; }
//        public string Username { get; set; }
//        public string Password { get; set; }
//    }
//}
